#!/usr/bin/env bash
# Write a TUI config file listing the models your environment actually enables.
#
#   docker exec agentcore-dev bash -lc 'scripts/local-dev/sync-models.sh'
#
# Why this exists: GET /models is cookie-session authenticated, so an API-key
# client cannot enumerate the catalogue at runtime (see tui/README.md). This
# reads the managed-models table directly — the same source /models serves —
# and writes the result into the TUI's config file.
#
# Requires AWS credentials with read access to the managed-models table.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ENV_FILE="${REPO_ROOT}/backend/src/.env"
CONFIG_FILE="${AGENTCORE_TUI_CONFIG:-${HOME}/.config/agentcore-tui/config.toml}"
BASE_URL="${AGENTCORE_BASE_URL:-http://127.0.0.1:8000}"

if [ ! -f "${ENV_FILE}" ]; then
    echo "[ERROR] ${ENV_FILE} not found." >&2
    exit 1
fi

table="$(grep -E '^DYNAMODB_MANAGED_MODELS_TABLE_NAME=' "${ENV_FILE}" | cut -d= -f2- || true)"
if [ -z "${table}" ]; then
    echo "[ERROR] DYNAMODB_MANAGED_MODELS_TABLE_NAME missing from ${ENV_FILE}." >&2
    exit 1
fi

# Honour AWS_PROFILE from .env so this matches what app-api itself uses.
profile="$(grep -E '^AWS_PROFILE=' "${ENV_FILE}" | cut -d= -f2- || true)"
[ -n "${profile}" ] && export AWS_PROFILE="${profile}"
region="$(grep -E '^AWS_REGION=' "${ENV_FILE}" | cut -d= -f2- || true)"
[ -n "${region}" ] && export AWS_REGION="${region}"

echo "[INFO] reading enabled models from ${table}"
mapfile -t models < <(
    aws dynamodb scan --table-name "${table}" \
        --filter-expression "enabled = :t" \
        --expression-attribute-values '{":t":{"BOOL":true}}' \
        --query "Items[].modelId.S" --output text 2>/dev/null | tr '\t' '\n' | sed '/^$/d' | sort
)

if [ "${#models[@]}" -eq 0 ]; then
    echo "[ERROR] no enabled models found in ${table}." >&2
    exit 1
fi

# Prefer a cheap default when present, else the first alphabetically.
default_model="${models[0]}"
for m in "${models[@]}"; do
    case "${m}" in *haiku*) default_model="${m}"; break ;; esac
done

mkdir -p "$(dirname "${CONFIG_FILE}")"
{
    echo "# GENERATED by scripts/local-dev/sync-models.sh"
    echo "# Models mirrored from ${table} (enabled = true)."
    echo
    echo "base_url = \"${BASE_URL}\""
    echo "model_id = \"${default_model}\""
    echo "models = ["
    for m in "${models[@]}"; do
        echo "    \"${m}\","
    done
    echo "]"
} > "${CONFIG_FILE}"
chmod 600 "${CONFIG_FILE}"

echo "[OK]   ${#models[@]} enabled models -> ${CONFIG_FILE}"
echo "[OK]   default model: ${default_model}"
printf '       %s\n' "${models[@]}"
